language: generic
sudo: required
services:
  - docker

deploy:
  provider: packagecloud
  repository: "ci"
  username: "ergw"
  token:
    secure: NoiePNR+qvXYzRjPwDzecT+sGgu6f/rCQ0YlgRgG+VqgUu2D01VaSR/iBx5q4gVFRzRdAZLJq2l6uzW/6twUaVX6veMCshKYjkiRjuZZ/+S2ETvJP6YdlwquRd94DNWGw18k/4lAuR11gzHwlfWalXLnBgqXn4N54Amw/NG+XXSqtEQBoMCYG4+1MpkIUwIa174SWQRfHFd9B6bFGTIc+xishTPEVdefAUjpb5p37gFcFZPnE2m8Sk7zAeX3t/MzILx9Q0lCu48dd6/JoFTM0LjSEtKHU+6L8N0dzBPFOis4WM3sH0OagR5l8E4vKwnkcKXbpznEkSWlxnSfC5OWAczldmpucQbyFp3MmzY3TZf41yeX0r1lu3YKN5jpU+ngZ8xRRGjpZ2RCGRakTl258xax/HTkkR8tFV9oMytzD7rFwC7vmkzDpo3ZdvpmJ/a5SP0ER6XGZnZH+S/uZp7e0I3Q1OnU1kJXgletRPm5rWySgs/Xj/YsEP05d2BAQsBmzKV542c0bzcYGXTbJo5iHwMt1KGK2SnRA+788GnhLp6ucvOFcLsnBfIJXuFMXa15yOUUBVjjzlMoqYvyyqXni+jOeB99P/4dzjJcQh9CTLAt00k7QVtH/9yAx3GCdy0P4SZn3iozHPdPsbdyVIXDqKsbpsRtcR2gQe5q1yNgNh4=
  dist: "ubuntu/xenial"
  skip_cleanup: true
  package_glob: artifacts/*.deb

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y devscripts
  - docker build -t ergw -f priv/Dockerfile priv

script:
  - export SHORT_COMMIT_ID=$(git rev-parse --verify --short $TRAVIS_COMMIT)
  - debchange -m -l "+$TRAVIS_JOB_NUMBER+git$SHORT_COMMIT_ID" 'Automatically built'
  - mkdir artifacts
  - docker run -v `pwd`:/build ergw
    sh -c "
      dpkg-buildpackage -b -uc && cp ../*deb artifacts
    "

notifications:
  slack:
  - secure: "k8ZbA09pgP3DVmtBIpx9FGkmSgrFXIICSR+UDPjHJ6nUUkL5bq3r4u2n+LeAMvkDxMHofJ+N5coL8CD3E5ztg6t8CM+/2h0HIfKT5sbdNZFA8jgn/pQ6oy5GW3mcNd7gIFLqxK7scV6eXBN7AJtOTKfbihMrMqojHc8qh3u1Zey6WYPZ9zx2Mm6yHbONxrat/8WZuHHRwA5r0NaHc/Ds468M2FFE5Rsshy49x6gF0Zw5bH+oEuirzOFqP/v7NUeDfVlOGxz63dETDf577FM/oAFluavjdtbzsltXeICOuXnb9fw48QDRUcytM0vdubngXO8gUu07P/5yQU6uu4+LLHKFtwTT8qj+UMiMyt9PAUroiLpWbPzQ28P5/STLiwTJh4otXkVO3jzLEMEFWHT3KYeh4oH6uVkwfpkRPPXR/2eTFBXrd5pRw3glwnrofOzgrOWE2o6Q1V8kqCak8UIOXvOsWPGPDmYgy2z+noE8GAlE4cbjRtnnWyehQSQBk4PJtyKkUVWv3KpCHJohpscWuiKH/MXxjDa9lsdgGQcOi+axUS1cbD5vn1/kmMemh16M10IH2WnW729Nj2pJ/D1fLEuMs3ZCVl2tDRFWtSQl/VqoOb0JLONoVAjEb3gchJiXXia2tG1auRM3DDECiOyKOMViH8XxvNY9uHg0WvVMJbs="

branches:
  only:
    - master