language: generic
sudo: required
services:
  - docker

deploy:
  provider: packagecloud
  repository: "ci"
  username: "ergw"
  token:
    secure: "vgb+gt1Bssno9SDX+dwrfnSk8q0RUjCQn715hC3pKp+kEclSPnKjqeSjESYjkpqZC/mK6MHeYIVoVSl41agTbnya7kkvTbQXyZRuq9mTUPbRhD5emXTv6cLPF0EgTXoTMmD8sCT2E6Y0vZwIQnooBCpknQoyOfIguhU1ERCRX9NpDh/9yXa6kkZZ7eKNKKWjZoVeJ3DgevjrbW1cip7vi7R5RKgtdMU87kIWRz21vae8x/FUyEhFPU7ephzF7D5LSohYC96xegtGmJztvVHP9eK+jW1oZjuNAJSim3pd3noxengdgB7r+zW70PvYlytknj09S/V2SA4UzG2RRYaP2UHIlotNB/48nK/YomsLPd+LB3YYIVLhytbiG0PXnph1Q668LcT8vFSwO2xWp712n1HAcvuC7TscIchCHMDj3TH5g3oipFUTIRuoX5WiUMeFHx6XVN1090+Z8pcxyryAQH7OfEEcQEfJFCX2ObyL9KU8WOPpvqodFe4AHZVFq/olqky74GqSWSEui7FBKiGUTaMQGhpdu6jazTGcoVOY5HBouvb9SqEGkMUk6681kgsGDqAjF1fAq8jZhdjZTRZeLcx3wchJ4Qvw8W0b/f+J/Q2LhnR3DlbfeWpxOkVByZ7R4l/XQxiBGw8fVZ0EHYvz8lJAV8S+p1ot6rmaWbQdLfc="

  dist: "ubuntu/xenial"
  skip_cleanup: true
  package_glob: artifacts/*.deb

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y devscripts
  - docker build -t ergw -f priv/Dockerfile priv

script:
  - export SHORT_COMMIT_ID=$(git rev-parse --verify --short $TRAVIS_COMMIT)
  - debchange -m -l "+$TRAVIS_JOB_NUMBER+git$SHORT_COMMIT_ID" 'Automatically built'
  - mkdir artifacts
  - docker run -v `pwd`:/build ergw
    sh -c "
      dpkg-buildpackage -b -uc && cp ../*deb artifacts
    "

notifications:
  slack:
  - secure: "k8ZbA09pgP3DVmtBIpx9FGkmSgrFXIICSR+UDPjHJ6nUUkL5bq3r4u2n+LeAMvkDxMHofJ+N5coL8CD3E5ztg6t8CM+/2h0HIfKT5sbdNZFA8jgn/pQ6oy5GW3mcNd7gIFLqxK7scV6eXBN7AJtOTKfbihMrMqojHc8qh3u1Zey6WYPZ9zx2Mm6yHbONxrat/8WZuHHRwA5r0NaHc/Ds468M2FFE5Rsshy49x6gF0Zw5bH+oEuirzOFqP/v7NUeDfVlOGxz63dETDf577FM/oAFluavjdtbzsltXeICOuXnb9fw48QDRUcytM0vdubngXO8gUu07P/5yQU6uu4+LLHKFtwTT8qj+UMiMyt9PAUroiLpWbPzQ28P5/STLiwTJh4otXkVO3jzLEMEFWHT3KYeh4oH6uVkwfpkRPPXR/2eTFBXrd5pRw3glwnrofOzgrOWE2o6Q1V8kqCak8UIOXvOsWPGPDmYgy2z+noE8GAlE4cbjRtnnWyehQSQBk4PJtyKkUVWv3KpCHJohpscWuiKH/MXxjDa9lsdgGQcOi+axUS1cbD5vn1/kmMemh16M10IH2WnW729Nj2pJ/D1fLEuMs3ZCVl2tDRFWtSQl/VqoOb0JLONoVAjEb3gchJiXXia2tG1auRM3DDECiOyKOMViH8XxvNY9uHg0WvVMJbs="

branches:
  only:
    - master