apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ergw-gtp
  labels:
    run: ergw-gtp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ergw-gtp
  template:
    metadata:
        labels:
          run: ergw-gtp
    spec:
      containers:
      - name: ergw-u-edp
        image: kiliandargel/ergw-gtp-u-edp
        volumeMounts:
       - name: gtp-u-edp-configmap
         mountPath: /config/       
      - name: ergw-c-node
        image: ergw/ergw-gtp-c-node
        volumeMounts:
       - name: gtp-c-edp-configmap
         mountPath: /config/
    volumes:
      - name: gtp-u-edp-config-volume
        configMap:
          name: gtp-u-edp-configmap
      - name: gtp-c-edp-config-volume
        configMap:
          name: gtp-c-edp-configmap
